[package]
name = "bot"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = "0.6.1"
serenity = "0.12.2"
tokio = { version = "1.40.0", features = ["full"] }

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-w64-mingw32-gcc"